events {}

http {
    log_format upstreamlog '$remote_addr -> $upstream_addr "$request" $status';
    access_log /var/log/nginx/access.log upstreamlog;

    upstream articleservice {
        server articleservice:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://articleservice;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}